### ISSUE TITLE
Panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by embano1** [ashleyschuett/kubeconfig-cleanup#5]
Hi,

Getting a panic directly after involvement. 

```bash
$ k plugin kubeconfig-cleanup
[kubeconfig] Using default path '$HOME/.kube/config'

| panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x19a6603]

goroutine 23 [running]:
github.com/ashleyschuett/kubeconfig-cleanup/vendor/k8s.io/client-go/kubernetes.(*Clientset).CoreV1(...)
        /Users/ashley/go/src/github.com/ashleyschuett/kubeconfig-cleanup/vendor/k8s.io/client-go/kubernetes/clientset.go:273
github.com/ashleyschuett/kubeconfig-cleanup/pkg/config.(*Manager).Validate(0xc420312940, 0xc42028f2c0, 0x0, 0x0, 0x0)
        /Users/ashley/go/src/github.com/ashleyschuett/kubeconfig-cleanup/pkg/config/config.go:164 +0x1a3
github.com/ashleyschuett/kubeconfig-cleanup/pkg/config.(*Manager).ValidateAndAddToWorkqueue(0xc420312940, 0xc4202befc0, 0x15, 0xc42028f2c0)
        /Users/ashley/go/src/github.com/ashleyschuett/kubeconfig-cleanup/pkg/config/workqueue.go:26 +0x3c
created by github.com/ashleyschuett/kubeconfig-cleanup/pkg/config.(*Manager).Run
        /Users/ashley/go/src/github.com/ashleyschuett/kubeconfig-cleanup/pkg/config/config.go:64 +0xc1
error: exit status 2
```

**Comment by ashleyschuett** [comment]
Is your kubeconfig file located at `$HOME/.kube/config`?

**Comment by embano1** [comment]
Yes, it's there.

Reading the stack trace the issue seems to be caused here:

```go
func (m *Manager) Validate(context *clientcmdapi.Context) (bool, string) {
[...]
_, err = client.CoreV1().ConfigMaps(metav1.NamespacePublic).Get(bootstrapapi.ConfigMapClusterInfo, metav1.GetOptions{})
https://github.com/ashleyschuett/kubeconfig-cleanup/blob/master/pkg/config/config.go#L164
```

calls: 

```go
// CoreV1 retrieves the CoreV1Client
func (c *Clientset) CoreV1() corev1.CoreV1Interface {
	return c.coreV1
}
https://github.com/kubernetes/client-go/blob/v7.0.0/kubernetes/clientset.go#L273
```

Could that be caused by using incompatible client-go and K8s versions? Just speculating...

**Comment by embano1** [comment]
Full stack trace attached:

interesting: 

```go
github.com/ashleyschuett/kubeconfig-cleanup/vendor/k8s.io/client-go/tools/clientcmd.(*DirectClientConfig).ClientConfig(0xc42031c0c0, 0x0, 0x0, 0x0)
        /Users/ashley/go/src/github.com/ashleyschuett/kubeconfig-cleanup/vendor/k8s.io/client-go/tools/clientcmd/client_config.go:143 +0x273
```

From my understand that call for function signature `func (config *DirectClientConfig) ClientConfig() (*restclient.Config, error)` does not return a valid memory alloc i.e. nil.

[stacktrace.txt](https://github.com/ashleyschuett/kubeconfig-cleanup/files/2183757/stacktrace.txt)

**Comment by embano1** [comment]
Further investigation:

The error from `kubeconfigutil.ToClientSet(configFromClusterInfo)` was not checked.
I added the following line:

```go
	configFromClusterInfo.AuthInfos[context.AuthInfo] = m.getContextsUser(context)
	client, err := kubeconfigutil.ToClientSet(configFromClusterInfo)
	if err != nil {
		return false, fmt.Sprintf("error converting to clientset: %v", err)
	}
```

This solves the nil pointer exception and throws the following error:

```bash
Testing context's 'mgasch01-prod-context' cluster...
error converting to clientset: failed to create API client: No Auth Provider found for name "oidc"
Remove 'mgasch01-prod-context' from context (Y/n)? ^C
```

Btw: I had issues building from `remotes/origin/HEAD   -> origin/master` with Glide. Go complained about incompatible types in the `Validate()` function. Using dep (which build dependency constraints from Glide, really neat) it worked.

**Comment by ashleyschuett** [comment]
Thank you for looking into this and fixing it

**Comment by embano1** [comment]
Welcome.

Since I did not push the binary, it's probably the best to create a new binary release containing this fix.
I usually use [Goreleaser](https://goreleaser.com/) as a way to automate releases.
